using System.Collections.Generic;
using UnityEngine;

namespace TileStories
{
    // A plain "(key, kind) -> asset" lookup asset (_3.1 step 13), same shape and role as SpriteKeyLibrary /
    // FontKeyLibrary: one Framework default (small, generated by our own scripts, no licence question) plus an
    // optional per-wall override, resolved the same way (wall first, then Framework) by CardMediaLibraryLookup. A
    // key holds at most one entry PER KIND (an audio clip and its .vtt captions share a key but are two entries,
    // same pairing rule ResourcesMediaSource already uses), so an Asset field's stored "default:<key>" resolves
    // unambiguously once its own MediaKind is known.
    [CreateAssetMenu(fileName = "CardMediaLibrary", menuName = "TileStories/Card Media Library")]
    public class CardMediaLibrary : ScriptableObject
    {
        [System.Serializable]
        public struct Entry
        {
            public string key;
            public MediaKind kind;
            public Object asset;
            // A short Editor-only note shown in the Default Media table's (i) -- never visitor text
            public string note;
        }

        [SerializeField] private List<Entry> entries = new();

        public IReadOnlyList<Entry> Entries => entries;

        public Object Get(string key, MediaKind kind)
        {
            if (string.IsNullOrEmpty(key)) return null;
            if (entries == null) return null;
            foreach (var e in entries)
                if (e.key == key && e.kind == kind && e.asset != null)
                    return e.asset;
            return null;
        }

        // Every key holding an entry of this kind (for the Editor's "Pick default..." picker)
        public IReadOnlyList<string> Keys(MediaKind kind)
        {
            var keys = new List<string>();
            if (entries == null) return keys;
            foreach (var e in entries)
                if (e.kind == kind && !string.IsNullOrEmpty(e.key) && e.asset != null)
                    keys.Add(e.key);
            return keys;
        }

        public bool HasKey(string key, MediaKind kind) => Get(key, kind) != null;

        // Adds or replaces the (key, kind) entry -- the generator script and the Editor's "Pick default..." /
        // wall-library flows use this, same shape as SpriteKeyLibrary.Set
        public void Set(string key, MediaKind kind, Object asset, string note = "")
        {
            if (string.IsNullOrWhiteSpace(key) || asset == null) return;
            entries ??= new List<Entry>();
            for (int i = 0; i < entries.Count; i++)
            {
                if (entries[i].key == key && entries[i].kind == kind)
                {
                    entries[i] = new Entry { key = key, kind = kind, asset = asset, note = note };
                    return;
                }
            }
            entries.Add(new Entry { key = key, kind = kind, asset = asset, note = note });
        }

        // Seeds a newly-created wall library with the Framework default's entries, same role as
        // SpriteKeyLibrary.CopyFrom / FontKeyLibrary.CopyFrom: a wall's own library REPLACES the Framework one
        // entirely at runtime, so it must start with everything the wall wants to keep.
        public void CopyFrom(CardMediaLibrary source)
        {
            entries ??= new List<Entry>();
            entries.Clear();
            if (source == null || source.Entries == null) return;
            foreach (var entry in source.Entries)
                entries.Add(entry);
        }
    }
}
