using System.Collections;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;

namespace TileStories.Tests
{
    // The REAL CardPreviewStage (_3.1 step 10A.2b.1): unlike CardPreviewServiceTests (a fake ManualPreviewStage, never
    // touching the scene), this drives the actual disabled camera + RenderTexture + instantiated model against the
    // Framework's own shipped default (`default:azulejo_arch`, generated by CardMediaLibraryGenerator, 10A.1). No
    // PoiCardHost wiring yet (10A.2b.2): the stage is exercised directly, standalone, on its own GameObject.
    public class CardPreviewStageTests
    {
        private GameObject _hostGo;
        private CardPreviewStage _stage;
        private ResourcesMediaSource _media;

        [SetUp]
        public void SetUp()
        {
            _hostGo = new GameObject("CardPreviewStageTestHost");
            _stage = _hostGo.AddComponent<CardPreviewStage>();
            _media = new ResourcesMediaSource("") { FrameworkDefaults = CardMediaLibraryLookup.Framework };
        }

        [TearDown]
        public void TearDown()
        {
            if (_hostGo != null) Object.Destroy(_hostGo);
        }

        [UnityTest]
        public IEnumerator Load_TheRealShippedDefaultModel_RendersNonEmptyPixels()
        {
            bool ready = false, failed = false;
            var handle = _stage.Load(MediaKind.Model, _media, "default:azulejo_arch", () => ready = true, () => failed = true);
            yield return null;

            Assert.IsTrue(ready, "the prefab resolves through Resources.Load: ready fires the same call");
            Assert.IsFalse(failed);
            Assert.IsNotNull(handle.Texture, "a RenderTexture handle for the view to draw");

            handle.RenderNow(TurntableState.Start, default);
            yield return null;

            var prev = RenderTexture.active;
            RenderTexture.active = handle.Texture;
            var pixels = new Texture2D(handle.Texture.width, handle.Texture.height, TextureFormat.RGBA32, false);
            pixels.ReadPixels(new Rect(0, 0, handle.Texture.width, handle.Texture.height), 0, 0);
            pixels.Apply();
            RenderTexture.active = prev;

            bool sawOpaquePixel = false;
            var raw = pixels.GetPixels32();
            foreach (var p in raw)
                if (p.a > 0) { sawOpaquePixel = true; break; }
            Object.Destroy(pixels);

            Assert.IsTrue(sawOpaquePixel, "the model actually rendered into the texture, not a blank/transparent frame");
            handle.Release();
        }

        [UnityTest]
        public IEnumerator Load_AMissingFile_CallsOnFailedExactlyOnce_NeverOnReady()
        {
            int readyCount = 0, failedCount = 0;
            var handle = _stage.Load(MediaKind.Model, _media, "models/this_file_does_not_exist.glb",
                () => readyCount++, () => failedCount++);
            yield return null;

            Assert.AreEqual(0, readyCount);
            Assert.AreEqual(1, failedCount);
            Assert.IsNull(handle.Texture);
            handle.Release(); // - a no-op on a failed handle, must not throw
        }

        // Counts scoped to this test's OWN host GameObject subtree, never the whole scene: a global
        // Resources.FindObjectsOfTypeAll/FindObjectsByType count is exactly the kind of absolute, order-dependent
        // measurement 40-testing.md 4.2.4b warns against -- in a full-suite run, URP/the Editor's own cameras
        // allocate and free RenderTextures of their own in the same frame window, which moved this count in a way
        // that had nothing to do with CardPreviewStage (observed once, full-suite only, never in isolation).
        private int GameObjectsUnderHost() => _hostGo.GetComponentsInChildren<Transform>(true).Length;

        [UnityTest]
        public IEnumerator Release_LeavesNoGameObjectMeshOrRenderTextureBehind()
        {
            int goBefore = GameObjectsUnderHost();

            var handle = _stage.Load(MediaKind.Model, _media, "default:azulejo_arch", null, null);
            yield return null;
            handle.RenderNow(TurntableState.Start, default);
            yield return null;

            int goDuring = GameObjectsUnderHost();
            var texture = handle.Texture;
            Assert.Greater(goDuring, goBefore, "the handle's own model + rig GameObjects exist while it's held");
            Assert.IsNotNull(texture, "the handle's own RenderTexture exists while it's held");
            Assert.IsFalse(texture == null, "and it is a real, non-destroyed Unity object");

            handle.Release();
            yield return null; // Destroy() applies at the end of the frame

            // - the stage's own shared rig (camera + lights, built once and reused across handles) stays under this
            // same host: only the per-handle root + model are expected gone, back to the rig-only baseline
            int goAfter = GameObjectsUnderHost();
            Assert.IsTrue(texture == null, "the RenderTexture itself was destroyed (Unity's overridden null check)");
            Assert.Less(goAfter, goDuring, "the handle's own GameObjects (model root + instantiated model) are gone");
        }
    }
}
