using System.Collections;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;

namespace TileStories.Tests
{
    // The REAL CardPreviewStage (_3.1 step 10A.2b.1): unlike CardPreviewServiceTests (a fake ManualPreviewStage, never
    // touching the scene), this drives the actual disabled camera + RenderTexture + instantiated model against the
    // Framework's own shipped default (`default:azulejo_arch`, generated by CardMediaLibraryGenerator, 10A.1). No
    // PoiCardHost wiring yet (10A.2b.2): the stage is exercised directly, standalone, on its own GameObject.
    public class CardPreviewStageTests
    {
        private GameObject _hostGo;
        private CardPreviewStage _stage;
        private ResourcesMediaSource _media;

        [SetUp]
        public void SetUp()
        {
            _hostGo = new GameObject("CardPreviewStageTestHost");
            _stage = _hostGo.AddComponent<CardPreviewStage>();
            _media = new ResourcesMediaSource("") { FrameworkDefaults = CardMediaLibraryLookup.Framework };
        }

        [TearDown]
        public void TearDown()
        {
            if (_hostGo != null) Object.Destroy(_hostGo);
        }

        [UnityTest]
        public IEnumerator Load_TheRealShippedDefaultModel_RendersNonEmptyPixels()
        {
            bool ready = false, failed = false;
            var handle = _stage.Load(MediaKind.Model, _media, "default:azulejo_arch", () => ready = true, () => failed = true);
            yield return null;

            Assert.IsTrue(ready, "the prefab resolves through Resources.Load: ready fires the same call");
            Assert.IsFalse(failed);
            Assert.IsNotNull(handle.Texture, "a RenderTexture handle for the view to draw");

            handle.RenderNow(TurntableState.Start, default);
            yield return null;

            var prev = RenderTexture.active;
            RenderTexture.active = handle.Texture;
            var pixels = new Texture2D(handle.Texture.width, handle.Texture.height, TextureFormat.RGBA32, false);
            pixels.ReadPixels(new Rect(0, 0, handle.Texture.width, handle.Texture.height), 0, 0);
            pixels.Apply();
            RenderTexture.active = prev;

            bool sawOpaquePixel = false;
            var raw = pixels.GetPixels32();
            foreach (var p in raw)
                if (p.a > 0) { sawOpaquePixel = true; break; }
            Object.Destroy(pixels);

            Assert.IsTrue(sawOpaquePixel, "the model actually rendered into the texture, not a blank/transparent frame");
            handle.Release();
        }

        // _3.1 10A.3-fix.2: the camera fits the model's bounding SPHERE (ModelFitRule), so no turn of the model can push a pixel
        // of it out of the picture. Drawn on a deliberately non-square stage (the real one is not square either), each model is
        // turned to several angles -- including the 90 degree turn that used to put the arch's base on the frame's edge -- and
        // its own drawn pixels must stay inside the stage with a margin (PreviewPixels.AssertDrawnInsideWithMargin).
        private static readonly (float Yaw, float Pitch)[] Turns = { (0f, 0f), (90f, 0f), (180f, 0f), (45f, 30f), (270f, -30f), (90f, 75f) };
        // At zoom 1 the model must still be a subject, not a speck: its widest turned pixels span at least 55 % of the sphere's
        // own diameter (the arch and the room scan measured 64 % and 63 % of the shorter side against the sphere's 80 %)
        private const float MinShareOfTheSphere = 0.55f;

        [UnityTest]
        public IEnumerator Load_TheFrameworkDefaultModel_StaysInsideTheStageAtEveryTurn_AndFillsItAtZoom1()
        {
            yield return AssertStaysInsideAtEveryTurn(_media, "default:azulejo_arch");
        }

        [UnityTest]
        public IEnumerator Load_TheLivingRoomRoomScanModel_StaysInsideTheStageAtEveryTurn_AndFillsItAtZoom1()
        {
            var livingRoomMedia = new ResourcesMediaSource("LivingRoom/CardMedia");
            yield return AssertStaysInsideAtEveryTurn(livingRoomMedia, "models/146267-LivingRoom2-tex.glb");
        }

        private IEnumerator AssertStaysInsideAtEveryTurn(IMediaSource media, string path)
        {
            var handle = _stage.Load(MediaKind.Model, media, path, null, null);
            yield return null;
            handle.Resize(360, 220); // landscape, on purpose: proves the fit follows the STAGE's real aspect
            int w = handle.Texture.width, h = handle.Texture.height;
            Assert.AreEqual(360, w, "precondition: the texture took the stage's size");
            int shorter = Mathf.Min(w, h);
            float widestSpan = 0f;
            foreach (var (yaw, pitch) in Turns)
            {
                handle.RenderNow(new TurntableState(yaw, pitch, 1f, 0f), default);
                yield return null;
                var drawn = PreviewPixels.AssertDrawnInsideWithMargin(handle.Texture, path + " at yaw " + yaw + " pitch " + pitch);
                widestSpan = Mathf.Max(widestSpan, Mathf.Max(drawn.width, drawn.height) / (float)shorter);
            }
            Assert.GreaterOrEqual(widestSpan, ModelFitRule.TargetFillOfShorterSide * MinShareOfTheSphere,
                path + ": the model draws as a speck (" + widestSpan.ToString("P0") + " of the shorter side)");

            handle.Release();
        }

        // ---------------- The Fit choice (_3.1 10B-pre.1): the solid arch and the hollow LivingRoom room scan ----------------

        private const string RoomScan = "models/146267-LivingRoom2-tex.glb";
        private const string Arch = "default:azulejo_arch";
        // Every yaw in 30 degree steps at the turntable's whole pitch range (its limits included)
        private static System.Collections.Generic.IEnumerable<(int Yaw, float Pitch)> AllowedTurns()
        {
            foreach (float pitch in new[] { TurntableRule.MinPitch, -40f, 0f, 40f, TurntableRule.MaxPitch })
                for (int yaw = 0; yaw < 360; yaw += 30) yield return (yaw, pitch);
        }

        // A model on the landscape test stage, framed by `mode`
        private IEnumerator LoadFitted(string path, ModelFitMode mode, System.Action<IPreviewHandle> got)
        {
            IMediaSource media = path == RoomScan ? new ResourcesMediaSource("LivingRoom/CardMedia") : _media;
            var handle = _stage.Load(MediaKind.Model, media, path, null, null);
            yield return null;
            handle.Resize(360, 220);
            handle.SetFit(mode);
            Assert.AreEqual(220, handle.Texture.height, "precondition: the texture took the stage's size");
            got(handle);
        }

        // What the model draws at the start angle
        private static IEnumerator DrawnAtRest(IPreviewHandle handle, System.Action<RectInt> got)
        {
            handle.RenderNow(TurntableState.Start, default);
            yield return null;
            got(PreviewPixels.DrawnBounds(handle.Texture));
        }

        private static IEnumerator AssertInsideAtEveryAllowedTurn(IPreviewHandle handle, string what)
        {
            foreach ((int yaw, float pitch) in AllowedTurns())
            {
                handle.RenderNow(new TurntableState(yaw, pitch, 1f, 0f), default);
                yield return null;
                PreviewPixels.AssertDrawnInsideWithMargin(handle.Texture, what + " at yaw " + yaw + " pitch " + pitch);
            }
        }

        // The hollow room scan's walls show only from inside, so from outside most of its box draws nothing: the box fits frame the
        // box, and Visible -- sized to the faces that face the camera -- is the option for it. Accepted 2026-10-01 (_3.1 10B-pre.1):
        // it draws the scan at 62 % of the shorter side (the brief's target was 65 %; what draws sits off-centre in the box, and the
        // orbit stays about the box centre so the model turns in place), so the promise asserted is "clearly larger than yaw_safe"
        [UnityTest]
        public IEnumerator Fit_Visible_DrawsTheHollowRoomScanAtLeast30PercentLargerThanYawSafe_AndStaysInsideAtEveryAllowedTurn()
        {
            IPreviewHandle handle = null;
            yield return LoadFitted(RoomScan, ModelFitMode.YawSafe, h => handle = h);
            RectInt yawSafe = default, visible = default;
            yield return DrawnAtRest(handle, r => yawSafe = r);
            handle.SetFit(ModelFitMode.Visible);
            yield return DrawnAtRest(handle, r => visible = r);
            Assert.GreaterOrEqual(visible.height, yawSafe.height * 1.3f, "visible draws the hollow scan larger: " + visible + " vs yaw_safe " + yawSafe);
            yield return AssertInsideAtEveryAllowedTurn(handle, "visible room scan");
            handle.Release();
        }

        [UnityTest]
        public IEnumerator Fit_YawSafe_StaysInsideAtEveryAllowedTurn_AndDrawsTheRoomScanAtLeastHalfAgainAsTallAsTheSphere()
        {
            IPreviewHandle handle = null;
            yield return LoadFitted(RoomScan, ModelFitMode.Sphere, h => handle = h);
            RectInt sphere = default, yawSafe = default;
            yield return DrawnAtRest(handle, r => sphere = r);
            yield return AssertInsideAtEveryAllowedTurn(handle, "sphere room scan");

            handle.SetFit(ModelFitMode.YawSafe);
            yield return DrawnAtRest(handle, r => yawSafe = r);
            Assert.GreaterOrEqual(yawSafe.height, sphere.height * 1.5f, "yaw_safe draws the long model larger than the sphere: " + yawSafe + " vs " + sphere);
            yield return AssertInsideAtEveryAllowedTurn(handle, "yaw_safe room scan");
            handle.Release();

            yield return LoadFitted(Arch, ModelFitMode.YawSafe, h => handle = h);
            yield return AssertInsideAtEveryAllowedTurn(handle, "yaw_safe arch");
            handle.Release();
        }

        [UnityTest]
        public IEnumerator Fit_AtRest_FillsAtLeast80PercentOfTheFrameAtRest_OnASolidModel()
        {
            IPreviewHandle handle = null;
            yield return LoadFitted(Arch, ModelFitMode.AtRest, h => handle = h);
            RectInt rest = default;
            yield return DrawnAtRest(handle, r => rest = r);
            float fill = Mathf.Max(rest.width / (float)handle.Texture.width, rest.height / (float)handle.Texture.height);
            Assert.GreaterOrEqual(fill, 0.8f, "at_rest: the arch fills " + fill.ToString("P0") + " of the frame on its binding axis, drawn " + rest);
            PreviewPixels.AssertDrawnInsideWithMargin(handle.Texture, "at_rest arch at rest");
            handle.Release();
        }

        [UnityTest]
        public IEnumerator Load_AMissingFile_CallsOnFailedExactlyOnce_NeverOnReady()
        {
            int readyCount = 0, failedCount = 0;
            var handle = _stage.Load(MediaKind.Model, _media, "models/this_file_does_not_exist.glb",
                () => readyCount++, () => failedCount++);
            yield return null;

            Assert.AreEqual(0, readyCount);
            Assert.AreEqual(1, failedCount);
            Assert.IsNull(handle.Texture);
            handle.Release(); // - a no-op on a failed handle, must not throw
        }

        // ---------------- panorama (10A.4.1): the stage's second subject, an inside-out sphere ----------------

        private const string DefaultPanorama = "default:tiled_room_360";

        private static int CountNamed<T>(string prefix) where T : Object
        {
            int n = 0;
            foreach (var o in Resources.FindObjectsOfTypeAll<T>()) if (o.name.StartsWith(prefix)) n++;
            return n;
        }

        // The middle of the stage, averaged over a small patch (one pixel of a tiled picture is noise): the panorama's colour at
        // the point the camera looks at
        private static Color CentrePatch(RenderTexture texture)
        {
            var box = new RectInt(texture.width / 2 - 4, texture.height / 2 - 4, 9, 9);
            float r = 0f, g = 0f, b = 0f;
            for (int y = box.yMin; y < box.yMax; y++)
                for (int x = box.xMin; x < box.xMax; x++)
                {
                    Color32 c = PreviewPixels.At(texture, x, y);
                    r += c.r; g += c.g; b += c.b;
                }
            float n = 255f * box.width * box.height;
            return new Color(r / n, g / n, b / n);
        }

        [UnityTest]
        public IEnumerator Panorama_TheShippedDefault_FillsEveryPixelOfTheStage_AndTheViewTurnsToADifferentWall()
        {
            bool ready = false, failed = false;
            var handle = _stage.Load(MediaKind.Panorama, _media, DefaultPanorama, () => ready = true, () => failed = true);
            yield return null;
            Assert.IsTrue(ready, "the default panorama resolves through the framework library");
            Assert.IsFalse(failed);
            handle.Resize(360, 220);

            handle.RenderNow(default, new PanoramaViewState(0f, 0f, PanoramaViewState.DefaultFov));
            yield return null;
            var drawn = PreviewPixels.DrawnBounds(handle.Texture);
            Assert.AreEqual(new RectInt(0, 0, 360, 220), drawn, "from inside a sphere every pixel of the stage shows the picture (no background left)");
            Color ahead = CentrePatch(handle.Texture);

            handle.RenderNow(default, new PanoramaViewState(180f, 0f, PanoramaViewState.DefaultFov));
            yield return null;
            Color behind = CentrePatch(handle.Texture);
            float difference = Mathf.Abs(ahead.r - behind.r) + Mathf.Abs(ahead.g - behind.g) + Mathf.Abs(ahead.b - behind.b);
            // - the generated room has a doorway ahead and a window behind (CardMediaLibraryGenerator.TiledRoom): not the same colour
            Assert.Greater(difference, 0.15f, "turned half way round the view shows another wall: ahead " + ahead + " behind " + behind);

            handle.Release();
        }

        [UnityTest]
        public IEnumerator Panorama_AheadIsThePicturesMiddle_TheViewSeesTheTextureItself()
        {
            var picture = _media.Load<Texture2D>(DefaultPanorama);
            Assert.IsNotNull(picture, "precondition: the default picture loads");
            // - a readable copy of the picture (the import keeps it GPU-only): the texel at the picture's middle, averaged over a patch
            var copy = new RenderTexture(picture.width, picture.height, 0);
            Graphics.Blit(picture, copy);
            var previous = RenderTexture.active;
            RenderTexture.active = copy;
            var readable = new Texture2D(picture.width, picture.height, TextureFormat.RGBA32, false);
            readable.ReadPixels(new Rect(0, 0, picture.width, picture.height), 0, 0);
            readable.Apply();
            RenderTexture.active = previous;
            Object.Destroy(copy);
            Color expected = Color.clear;
            for (int dy = -4; dy <= 4; dy++)
                for (int dx = -4; dx <= 4; dx++) expected += readable.GetPixel(picture.width / 2 + dx, picture.height / 2 + dy);
            expected /= 81f;
            Object.Destroy(readable);
            _media.Release(DefaultPanorama);

            var handle = _stage.Load(MediaKind.Panorama, _media, DefaultPanorama, null, null);
            yield return null;
            handle.RenderNow(default, new PanoramaViewState(0f, 0f, PanoramaViewState.DefaultFov));
            yield return null;
            Color seen = CentrePatch(handle.Texture);
            // - an unlit material, the picture sampled as it is: the same colour to within filtering and the 8-bit round trip
            Assert.AreEqual(expected.r, seen.r, 0.06f, "red: the view ahead shows the picture's middle. expected " + expected + " seen " + seen);
            Assert.AreEqual(expected.g, seen.g, 0.06f, "green");
            Assert.AreEqual(expected.b, seen.b, 0.06f, "blue");
            handle.Release();
        }

        [UnityTest]
        public IEnumerator Panorama_AWiderFieldOfView_ShowsMoreOfThePicture_ThanANarrowerOne()
        {
            var handle = _stage.Load(MediaKind.Panorama, _media, DefaultPanorama, null, null);
            yield return null;
            handle.Resize(360, 220);
            handle.RenderNow(default, new PanoramaViewState(0f, 0f, PanoramaViewRule.MinFov));
            yield return null;
            Color narrow = PreviewPixels.Average(handle.Texture);
            handle.RenderNow(default, new PanoramaViewState(0f, 0f, PanoramaViewRule.MaxFov));
            yield return null;
            Color wide = PreviewPixels.Average(handle.Texture);
            float difference = Mathf.Abs(narrow.r - wide.r) + Mathf.Abs(narrow.g - wide.g) + Mathf.Abs(narrow.b - wide.b);
            Assert.Greater(difference, 0.02f, "a different field of view changes what the whole stage shows: narrow " + narrow + " wide " + wide);
            handle.Release();
        }

        [UnityTest]
        public IEnumerator Panorama_AMissingFile_CallsOnFailedExactlyOnce_NeverOnReady()
        {
            int readyCount = 0, failedCount = 0;
            var handle = _stage.Load(MediaKind.Panorama, _media, "panoramas/this_file_does_not_exist.jpg", () => readyCount++, () => failedCount++);
            yield return null;
            Assert.AreEqual(0, readyCount);
            Assert.AreEqual(1, failedCount);
            Assert.IsNull(handle.Texture);
            handle.RenderNow(default, default); // a no-op on a failed handle, must not throw
            handle.Release();
        }

        [UnityTest]
        public IEnumerator Panorama_Release_LeavesNoSphereMeshMaterialOrTextureBehind()
        {
            int meshesBefore = CountNamed<Mesh>("CardPanoramaSphere_");
            int materialsBefore = CountNamed<Material>("CardPanorama_");
            int texturesBefore = CountNamed<RenderTexture>("CardPreview_");

            var handle = _stage.Load(MediaKind.Panorama, _media, DefaultPanorama, null, null);
            yield return null;
            handle.Resize(300, 200); // a resized texture is released too
            handle.RenderNow(default, PanoramaViewState.Start);
            yield return null;
            Assert.AreEqual(meshesBefore + 1, CountNamed<Mesh>("CardPanoramaSphere_"), "precondition: the handle's sphere mesh exists while it is held");
            Assert.AreEqual(materialsBefore + 1, CountNamed<Material>("CardPanorama_"), "and its own material");
            Assert.AreEqual(texturesBefore + 1, CountNamed<RenderTexture>("CardPreview_"), "and one RenderTexture");
            int objectsHeld = GameObjectsUnderHost();

            handle.Release();
            yield return null; // Destroy() applies at the end of the frame

            Assert.AreEqual(meshesBefore, CountNamed<Mesh>("CardPanoramaSphere_"), "the sphere mesh is gone");
            Assert.AreEqual(materialsBefore, CountNamed<Material>("CardPanorama_"), "the material instance is gone");
            Assert.AreEqual(texturesBefore, CountNamed<RenderTexture>("CardPreview_"), "the RenderTexture is gone");
            Assert.Less(GameObjectsUnderHost(), objectsHeld, "the handle's root and sphere GameObjects are gone");
            handle.Release(); // a second Release is harmless
        }

        [UnityTest]
        public IEnumerator ModelAndPanoramaHandles_HeldTogether_DoNotShowUpBehindEachOther()
        {
            // A model's camera looking along the stage's X axis (yaw 90) used to have a neighbour handle 50 m away in its view; the
            // far plane now ends at the model's own sphere, so the picture is the same with a panorama slot beside it or without.
            var model = _stage.Load(MediaKind.Model, _media, "default:azulejo_arch", null, null);
            yield return null;
            model.Resize(300, 200);
            var turn = new TurntableState(90f, 0f, 1f, 0f);
            model.RenderNow(turn, default);
            yield return null;
            var alone = PreviewPixels.DrawnBounds(model.Texture);

            var panorama = _stage.Load(MediaKind.Panorama, _media, DefaultPanorama, null, null);
            yield return null;
            model.RenderNow(turn, default);
            yield return null;
            Assert.AreEqual(alone, PreviewPixels.DrawnBounds(model.Texture), "with a panorama slot beside it the model's picture is unchanged");

            panorama.Release();
            model.Release();
        }

        // Counts scoped to this test's OWN host GameObject subtree, never the whole scene: a global
        // Resources.FindObjectsOfTypeAll/FindObjectsByType count is exactly the kind of absolute, order-dependent
        // measurement 40-testing.md 4.2.4b warns against -- in a full-suite run, URP/the Editor's own cameras
        // allocate and free RenderTextures of their own in the same frame window, which moved this count in a way
        // that had nothing to do with CardPreviewStage (observed once, full-suite only, never in isolation).
        private int GameObjectsUnderHost() => _hostGo.GetComponentsInChildren<Transform>(true).Length;

        [UnityTest]
        public IEnumerator Release_LeavesNoGameObjectMeshOrRenderTextureBehind()
        {
            int goBefore = GameObjectsUnderHost();

            var handle = _stage.Load(MediaKind.Model, _media, "default:azulejo_arch", null, null);
            yield return null;
            handle.RenderNow(TurntableState.Start, default);
            yield return null;

            int goDuring = GameObjectsUnderHost();
            var texture = handle.Texture;
            Assert.Greater(goDuring, goBefore, "the handle's own model + rig GameObjects exist while it's held");
            Assert.IsNotNull(texture, "the handle's own RenderTexture exists while it's held");
            Assert.IsFalse(texture == null, "and it is a real, non-destroyed Unity object");

            handle.Release();
            yield return null; // Destroy() applies at the end of the frame

            // - the stage's own shared rig (camera + lights, built once and reused across handles) stays under this
            // same host: only the per-handle root + model are expected gone, back to the rig-only baseline
            int goAfter = GameObjectsUnderHost();
            Assert.IsTrue(texture == null, "the RenderTexture itself was destroyed (Unity's overridden null check)");
            Assert.Less(goAfter, goDuring, "the handle's own GameObjects (model root + instantiated model) are gone");
        }
    }
}
